default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: GAMY_development

test:
  <<: *default
  database: GAMY_test

production:
  <<: *default
  database: GAMY_production
  username: GAMY
  password: <%= ENV["GAMY_DATABASE_PASSWORD"] %>
